/**
 * layout.jsx
 */

import NextAuthProvider from "@/components/providers/next-auth-provider";
import "./globals.css";
// import { Inter } from "next/font/google";
import MainNav from "@/components/navigation/main-nav";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import { ThemeProvider } from "@/components/providers/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const session = getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="transition-transform duration-50">
        <NextAuthProvider session={session}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <main>
              <MainNav />
              {children}
            </main>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
