/**
 * layout.jsx
 */

import NextAuthProvider from "@/components/providers/next-auth-provider";
import "./globals.css";
// import { Inter } from "next/font/google";
import MainNav from "@/components/navigation/main-nav";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import { ThemeProvider } from "@/components/providers/theme-provider";
import QueryProvider from "@/components/providers/query-provider";
// import WindowHistory from "@/components/providers/window-history";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="transition-transform duration-200 dark:bg-gray-900">
        <NextAuthProvider session={session}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <QueryProvider>
              <main className="">
                <MainNav session={session} />
                {children}
              </main>
            </QueryProvider>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
